use chrono::NaiveDateTime;

mod db;
pub use db::{DBArgs, DB};

mod migration;

/// models are generated by sea-orm-cli with Entity and Relation definitions.
pub mod models;

pub mod deploy_task;
/// All tables operation mod
pub mod deployment;
pub mod playground;
pub mod project;
pub mod settings;
pub mod storage;
pub mod user_info;
pub mod user_token;
pub mod worker;

fn now_time() -> NaiveDateTime {
    chrono::Utc::now().naive_utc()
}

pub type DateTimeUTC = chrono::DateTime<chrono::Utc>;
