// Generated by `wit-bindgen` 0.13.0. DO NOT EDIT!
pub mod land {
    pub mod http {

        #[allow(clippy::all)]
        pub mod http_types {
            #[used]
            #[doc(hidden)]
            #[cfg(target_arch = "wasm32")]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_section;
            pub type HttpStatusCode = u16;
            pub type HttpMethod = wit_bindgen::rt::string::String;
            pub type HttpHeaders = wit_bindgen::rt::vec::Vec<(
                wit_bindgen::rt::string::String,
                wit_bindgen::rt::string::String,
            )>;
            pub type HttpUri = wit_bindgen::rt::string::String;
            pub type HttpBodyHandle = u32;
            #[derive(Clone)]
            pub struct Request {
                pub method: HttpMethod,
                pub uri: HttpUri,
                pub headers: HttpHeaders,
                pub body: Option<HttpBodyHandle>,
            }
            impl ::core::fmt::Debug for Request {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("Request")
                        .field("method", &self.method)
                        .field("uri", &self.uri)
                        .field("headers", &self.headers)
                        .field("body", &self.body)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct Response {
                pub status: HttpStatusCode,
                pub headers: HttpHeaders,
                pub body: Option<HttpBodyHandle>,
            }
            impl ::core::fmt::Debug for Response {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("Response")
                        .field("status", &self.status)
                        .field("headers", &self.headers)
                        .field("body", &self.body)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, PartialEq)]
            pub enum RequestError {
                NetworkError,
                Timeout,
                InvalidUrl,
                DestinationNotAllowed,
                TooManyRequests,
                InvalidRequest,
            }
            impl RequestError {
                pub fn name(&self) -> &'static str {
                    match self {
                        RequestError::NetworkError => "network-error",
                        RequestError::Timeout => "timeout",
                        RequestError::InvalidUrl => "invalid-url",
                        RequestError::DestinationNotAllowed => "destination-not-allowed",
                        RequestError::TooManyRequests => "too-many-requests",
                        RequestError::InvalidRequest => "invalid-request",
                    }
                }
                pub fn message(&self) -> &'static str {
                    match self {
                        RequestError::NetworkError => "",
                        RequestError::Timeout => "",
                        RequestError::InvalidUrl => "",
                        RequestError::DestinationNotAllowed => "",
                        RequestError::TooManyRequests => "",
                        RequestError::InvalidRequest => "",
                    }
                }
            }
            impl ::core::fmt::Debug for RequestError {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("RequestError")
                        .field("code", &(*self as i32))
                        .field("name", &self.name())
                        .field("message", &self.message())
                        .finish()
                }
            }
            impl ::core::fmt::Display for RequestError {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    write!(f, "{} (error {})", self.name(), *self as i32)
                }
            }

            impl std::error::Error for RequestError {}

            impl RequestError {
                pub(crate) unsafe fn _lift(val: u8) -> RequestError {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }

                    match val {
                        0 => RequestError::NetworkError,
                        1 => RequestError::Timeout,
                        2 => RequestError::InvalidUrl,
                        3 => RequestError::DestinationNotAllowed,
                        4 => RequestError::TooManyRequests,
                        5 => RequestError::InvalidRequest,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }

            #[repr(u8)]
            #[derive(Clone, Copy, Eq, PartialEq)]
            pub enum RedirectPolicy {
                Follow,
                Error,
                Manual,
            }
            impl ::core::fmt::Debug for RedirectPolicy {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    match self {
                        RedirectPolicy::Follow => f.debug_tuple("RedirectPolicy::Follow").finish(),
                        RedirectPolicy::Error => f.debug_tuple("RedirectPolicy::Error").finish(),
                        RedirectPolicy::Manual => f.debug_tuple("RedirectPolicy::Manual").finish(),
                    }
                }
            }

            impl RedirectPolicy {
                pub(crate) unsafe fn _lift(val: u8) -> RedirectPolicy {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }

                    match val {
                        0 => RedirectPolicy::Follow,
                        1 => RedirectPolicy::Error,
                        2 => RedirectPolicy::Manual,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }

            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct RequestOptions {
                pub timeout: u32,
                pub redirect: RedirectPolicy,
            }
            impl ::core::fmt::Debug for RequestOptions {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("RequestOptions")
                        .field("timeout", &self.timeout)
                        .field("redirect", &self.redirect)
                        .finish()
                }
            }
        }

        #[allow(clippy::all)]
        pub mod http_body {
            #[used]
            #[doc(hidden)]
            #[cfg(target_arch = "wasm32")]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_section;
            pub type HttpBodyHandle = super::super::super::land::http::http_types::HttpBodyHandle;
            /// an error type returned from a body operation.
            #[derive(Clone)]
            pub enum BodyError {
                /// The body is invalid
                InvalidHandle,
                /// The body is only readable
                ReadOnly,
                /// The body read failed
                ReadFailed(wit_bindgen::rt::string::String),
                /// The body write failed
                WriteFailed(wit_bindgen::rt::string::String),
            }
            impl ::core::fmt::Debug for BodyError {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    match self {
                        BodyError::InvalidHandle => {
                            f.debug_tuple("BodyError::InvalidHandle").finish()
                        }
                        BodyError::ReadOnly => f.debug_tuple("BodyError::ReadOnly").finish(),
                        BodyError::ReadFailed(e) => {
                            f.debug_tuple("BodyError::ReadFailed").field(e).finish()
                        }
                        BodyError::WriteFailed(e) => {
                            f.debug_tuple("BodyError::WriteFailed").field(e).finish()
                        }
                    }
                }
            }
            impl ::core::fmt::Display for BodyError {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }

            impl std::error::Error for BodyError {}
            #[allow(clippy::all)]
            /// Read http body bytes with size and eof flag
            pub fn http_body_read(
                handle: HttpBodyHandle,
            ) -> Result<(wit_bindgen::rt::vec::Vec<u8>, bool), BodyError> {
                #[allow(unused_imports)]
                use wit_bindgen::rt::{alloc, string::String, vec::Vec};
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([u8; 16]);
                    let mut ret_area = ::core::mem::MaybeUninit::<RetArea>::uninit();
                    let ptr0 = ret_area.as_mut_ptr() as i32;
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "land:http/http-body")]
                    extern "C" {
                        #[link_name = "http-body-read"]
                        fn wit_import(_: i32, _: i32);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: i32, _: i32) {
                        unreachable!()
                    }
                    wit_import(wit_bindgen::rt::as_i32(handle), ptr0);
                    let l1 = i32::from(*((ptr0 + 0) as *const u8));
                    match l1 {
                        0 => {
                            let e = {
                                let l2 = *((ptr0 + 4) as *const i32);
                                let l3 = *((ptr0 + 8) as *const i32);
                                let len4 = l3 as usize;
                                let l5 = i32::from(*((ptr0 + 12) as *const u8));

                                (
                                    Vec::from_raw_parts(l2 as *mut _, len4, len4),
                                    wit_bindgen::rt::bool_lift(l5 as u8),
                                )
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l6 = i32::from(*((ptr0 + 4) as *const u8));
                                let v13 = match l6 {
                                    0 => BodyError::InvalidHandle,
                                    1 => BodyError::ReadOnly,
                                    2 => {
                                        let e13 = {
                                            let l7 = *((ptr0 + 8) as *const i32);
                                            let l8 = *((ptr0 + 12) as *const i32);
                                            let len9 = l8 as usize;
                                            let bytes9 =
                                                Vec::from_raw_parts(l7 as *mut _, len9, len9);

                                            wit_bindgen::rt::string_lift(bytes9)
                                        };
                                        BodyError::ReadFailed(e13)
                                    }
                                    n => {
                                        debug_assert_eq!(n, 3, "invalid enum discriminant");
                                        let e13 = {
                                            let l10 = *((ptr0 + 8) as *const i32);
                                            let l11 = *((ptr0 + 12) as *const i32);
                                            let len12 = l11 as usize;
                                            let bytes12 =
                                                Vec::from_raw_parts(l10 as *mut _, len12, len12);

                                            wit_bindgen::rt::string_lift(bytes12)
                                        };
                                        BodyError::WriteFailed(e13)
                                    }
                                };

                                v13
                            };
                            Err(e)
                        }
                        _ => wit_bindgen::rt::invalid_enum_discriminant(),
                    }
                }
            }
            #[allow(clippy::all)]
            /// Readall http body bytes with size and eof flag
            pub fn http_body_read_all(
                handle: HttpBodyHandle,
            ) -> Result<wit_bindgen::rt::vec::Vec<u8>, BodyError> {
                #[allow(unused_imports)]
                use wit_bindgen::rt::{alloc, string::String, vec::Vec};
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([u8; 16]);
                    let mut ret_area = ::core::mem::MaybeUninit::<RetArea>::uninit();
                    let ptr0 = ret_area.as_mut_ptr() as i32;
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "land:http/http-body")]
                    extern "C" {
                        #[link_name = "http-body-read-all"]
                        fn wit_import(_: i32, _: i32);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: i32, _: i32) {
                        unreachable!()
                    }
                    wit_import(wit_bindgen::rt::as_i32(handle), ptr0);
                    let l1 = i32::from(*((ptr0 + 0) as *const u8));
                    match l1 {
                        0 => {
                            let e = {
                                let l2 = *((ptr0 + 4) as *const i32);
                                let l3 = *((ptr0 + 8) as *const i32);
                                let len4 = l3 as usize;

                                Vec::from_raw_parts(l2 as *mut _, len4, len4)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l5 = i32::from(*((ptr0 + 4) as *const u8));
                                let v12 = match l5 {
                                    0 => BodyError::InvalidHandle,
                                    1 => BodyError::ReadOnly,
                                    2 => {
                                        let e12 = {
                                            let l6 = *((ptr0 + 8) as *const i32);
                                            let l7 = *((ptr0 + 12) as *const i32);
                                            let len8 = l7 as usize;
                                            let bytes8 =
                                                Vec::from_raw_parts(l6 as *mut _, len8, len8);

                                            wit_bindgen::rt::string_lift(bytes8)
                                        };
                                        BodyError::ReadFailed(e12)
                                    }
                                    n => {
                                        debug_assert_eq!(n, 3, "invalid enum discriminant");
                                        let e12 = {
                                            let l9 = *((ptr0 + 8) as *const i32);
                                            let l10 = *((ptr0 + 12) as *const i32);
                                            let len11 = l10 as usize;
                                            let bytes11 =
                                                Vec::from_raw_parts(l9 as *mut _, len11, len11);

                                            wit_bindgen::rt::string_lift(bytes11)
                                        };
                                        BodyError::WriteFailed(e12)
                                    }
                                };

                                v12
                            };
                            Err(e)
                        }
                        _ => wit_bindgen::rt::invalid_enum_discriminant(),
                    }
                }
            }
            #[allow(clippy::all)]
            /// Write http body bytes, return written bytes length
            pub fn http_body_write(handle: HttpBodyHandle, data: &[u8]) -> Result<u64, BodyError> {
                #[allow(unused_imports)]
                use wit_bindgen::rt::{alloc, string::String, vec::Vec};
                unsafe {
                    #[repr(align(8))]
                    struct RetArea([u8; 24]);
                    let mut ret_area = ::core::mem::MaybeUninit::<RetArea>::uninit();
                    let vec0 = data;
                    let ptr0 = vec0.as_ptr() as i32;
                    let len0 = vec0.len() as i32;
                    let ptr1 = ret_area.as_mut_ptr() as i32;
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "land:http/http-body")]
                    extern "C" {
                        #[link_name = "http-body-write"]
                        fn wit_import(_: i32, _: i32, _: i32, _: i32);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: i32, _: i32, _: i32, _: i32) {
                        unreachable!()
                    }
                    wit_import(wit_bindgen::rt::as_i32(handle), ptr0, len0, ptr1);
                    let l2 = i32::from(*((ptr1 + 0) as *const u8));
                    match l2 {
                        0 => {
                            let e = {
                                let l3 = *((ptr1 + 8) as *const i64);

                                l3 as u64
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l4 = i32::from(*((ptr1 + 8) as *const u8));
                                let v11 = match l4 {
                                    0 => BodyError::InvalidHandle,
                                    1 => BodyError::ReadOnly,
                                    2 => {
                                        let e11 = {
                                            let l5 = *((ptr1 + 12) as *const i32);
                                            let l6 = *((ptr1 + 16) as *const i32);
                                            let len7 = l6 as usize;
                                            let bytes7 =
                                                Vec::from_raw_parts(l5 as *mut _, len7, len7);

                                            wit_bindgen::rt::string_lift(bytes7)
                                        };
                                        BodyError::ReadFailed(e11)
                                    }
                                    n => {
                                        debug_assert_eq!(n, 3, "invalid enum discriminant");
                                        let e11 = {
                                            let l8 = *((ptr1 + 12) as *const i32);
                                            let l9 = *((ptr1 + 16) as *const i32);
                                            let len10 = l9 as usize;
                                            let bytes10 =
                                                Vec::from_raw_parts(l8 as *mut _, len10, len10);

                                            wit_bindgen::rt::string_lift(bytes10)
                                        };
                                        BodyError::WriteFailed(e11)
                                    }
                                };

                                v11
                            };
                            Err(e)
                        }
                        _ => wit_bindgen::rt::invalid_enum_discriminant(),
                    }
                }
            }
            #[allow(clippy::all)]
            /// Accquire http body and get http body handle
            pub fn http_body_new() -> Result<HttpBodyHandle, BodyError> {
                #[allow(unused_imports)]
                use wit_bindgen::rt::{alloc, string::String, vec::Vec};
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([u8; 16]);
                    let mut ret_area = ::core::mem::MaybeUninit::<RetArea>::uninit();
                    let ptr0 = ret_area.as_mut_ptr() as i32;
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "land:http/http-body")]
                    extern "C" {
                        #[link_name = "http-body-new"]
                        fn wit_import(_: i32);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: i32) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = i32::from(*((ptr0 + 0) as *const u8));
                    match l1 {
                        0 => {
                            let e = {
                                let l2 = *((ptr0 + 4) as *const i32);

                                l2 as u32
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l3 = i32::from(*((ptr0 + 4) as *const u8));
                                let v10 = match l3 {
                                    0 => BodyError::InvalidHandle,
                                    1 => BodyError::ReadOnly,
                                    2 => {
                                        let e10 = {
                                            let l4 = *((ptr0 + 8) as *const i32);
                                            let l5 = *((ptr0 + 12) as *const i32);
                                            let len6 = l5 as usize;
                                            let bytes6 =
                                                Vec::from_raw_parts(l4 as *mut _, len6, len6);

                                            wit_bindgen::rt::string_lift(bytes6)
                                        };
                                        BodyError::ReadFailed(e10)
                                    }
                                    n => {
                                        debug_assert_eq!(n, 3, "invalid enum discriminant");
                                        let e10 = {
                                            let l7 = *((ptr0 + 8) as *const i32);
                                            let l8 = *((ptr0 + 12) as *const i32);
                                            let len9 = l8 as usize;
                                            let bytes9 =
                                                Vec::from_raw_parts(l7 as *mut _, len9, len9);

                                            wit_bindgen::rt::string_lift(bytes9)
                                        };
                                        BodyError::WriteFailed(e10)
                                    }
                                };

                                v10
                            };
                            Err(e)
                        }
                        _ => wit_bindgen::rt::invalid_enum_discriminant(),
                    }
                }
            }
            #[allow(clippy::all)]
            /// Accquire http body and get http body handle
            pub fn http_body_new_stream() -> Result<HttpBodyHandle, BodyError> {
                #[allow(unused_imports)]
                use wit_bindgen::rt::{alloc, string::String, vec::Vec};
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([u8; 16]);
                    let mut ret_area = ::core::mem::MaybeUninit::<RetArea>::uninit();
                    let ptr0 = ret_area.as_mut_ptr() as i32;
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "land:http/http-body")]
                    extern "C" {
                        #[link_name = "http-body-new-stream"]
                        fn wit_import(_: i32);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: i32) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = i32::from(*((ptr0 + 0) as *const u8));
                    match l1 {
                        0 => {
                            let e = {
                                let l2 = *((ptr0 + 4) as *const i32);

                                l2 as u32
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l3 = i32::from(*((ptr0 + 4) as *const u8));
                                let v10 = match l3 {
                                    0 => BodyError::InvalidHandle,
                                    1 => BodyError::ReadOnly,
                                    2 => {
                                        let e10 = {
                                            let l4 = *((ptr0 + 8) as *const i32);
                                            let l5 = *((ptr0 + 12) as *const i32);
                                            let len6 = l5 as usize;
                                            let bytes6 =
                                                Vec::from_raw_parts(l4 as *mut _, len6, len6);

                                            wit_bindgen::rt::string_lift(bytes6)
                                        };
                                        BodyError::ReadFailed(e10)
                                    }
                                    n => {
                                        debug_assert_eq!(n, 3, "invalid enum discriminant");
                                        let e10 = {
                                            let l7 = *((ptr0 + 8) as *const i32);
                                            let l8 = *((ptr0 + 12) as *const i32);
                                            let len9 = l8 as usize;
                                            let bytes9 =
                                                Vec::from_raw_parts(l7 as *mut _, len9, len9);

                                            wit_bindgen::rt::string_lift(bytes9)
                                        };
                                        BodyError::WriteFailed(e10)
                                    }
                                };

                                v10
                            };
                            Err(e)
                        }
                        _ => wit_bindgen::rt::invalid_enum_discriminant(),
                    }
                }
            }
        }

        #[allow(clippy::all)]
        pub mod http_outgoing {
            #[used]
            #[doc(hidden)]
            #[cfg(target_arch = "wasm32")]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_section;
            pub type Request = super::super::super::land::http::http_types::Request;
            pub type Response = super::super::super::land::http::http_types::Response;
            pub type RequestError = super::super::super::land::http::http_types::RequestError;
            pub type RequestOptions = super::super::super::land::http::http_types::RequestOptions;
            #[allow(clippy::all)]
            pub fn fetch_request(
                req: &Request,
                options: RequestOptions,
            ) -> Result<Response, RequestError> {
                #[allow(unused_imports)]
                use wit_bindgen::rt::{alloc, string::String, vec::Vec};
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([u8; 24]);
                    let mut ret_area = ::core::mem::MaybeUninit::<RetArea>::uninit();
                    let super::super::super::land::http::http_types::Request {
                        method: method0,
                        uri: uri0,
                        headers: headers0,
                        body: body0,
                    } = req;
                    let vec1 = method0;
                    let ptr1 = vec1.as_ptr() as i32;
                    let len1 = vec1.len() as i32;
                    let vec2 = uri0;
                    let ptr2 = vec2.as_ptr() as i32;
                    let len2 = vec2.len() as i32;
                    let vec6 = headers0;
                    let len6 = vec6.len() as i32;
                    let layout6 = alloc::Layout::from_size_align_unchecked(vec6.len() * 16, 4);
                    let result6 = if layout6.size() != 0 {
                        let ptr = alloc::alloc(layout6);
                        if ptr.is_null() {
                            alloc::handle_alloc_error(layout6);
                        }
                        ptr
                    } else {
                        {
                            ::core::ptr::null_mut()
                        }
                    };
                    for (i, e) in vec6.into_iter().enumerate() {
                        let base = result6 as i32 + (i as i32) * 16;
                        {
                            let (t3_0, t3_1) = e;
                            let vec4 = t3_0;
                            let ptr4 = vec4.as_ptr() as i32;
                            let len4 = vec4.len() as i32;
                            *((base + 4) as *mut i32) = len4;
                            *((base + 0) as *mut i32) = ptr4;
                            let vec5 = t3_1;
                            let ptr5 = vec5.as_ptr() as i32;
                            let len5 = vec5.len() as i32;
                            *((base + 12) as *mut i32) = len5;
                            *((base + 8) as *mut i32) = ptr5;
                        }
                    }
                    let (result7_0, result7_1) = match body0 {
                        Some(e) => (1i32, wit_bindgen::rt::as_i32(e)),
                        None => (0i32, 0i32),
                    };
                    let super::super::super::land::http::http_types::RequestOptions {
                        timeout: timeout8,
                        redirect: redirect8,
                    } = options;
                    let ptr9 = ret_area.as_mut_ptr() as i32;
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "land:http/http-outgoing")]
                    extern "C" {
                        #[link_name = "fetch-request"]
                        fn wit_import(
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                        );
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                    ) {
                        unreachable!()
                    }
                    wit_import(
                        ptr1,
                        len1,
                        ptr2,
                        len2,
                        result6 as i32,
                        len6,
                        result7_0,
                        result7_1,
                        wit_bindgen::rt::as_i32(timeout8),
                        redirect8.clone() as i32,
                        ptr9,
                    );
                    let l10 = i32::from(*((ptr9 + 0) as *const u8));
                    if layout6.size() != 0 {
                        alloc::dealloc(result6, layout6);
                    }
                    match l10 {
                        0 => {
                            let e = {
                                let l11 = i32::from(*((ptr9 + 4) as *const u16));
                                let l12 = *((ptr9 + 8) as *const i32);
                                let l13 = *((ptr9 + 12) as *const i32);
                                let base20 = l12;
                                let len20 = l13;
                                let mut result20 = Vec::with_capacity(len20 as usize);
                                for i in 0..len20 {
                                    let base = base20 + i * 16;
                                    let e20 = {
                                        let l14 = *((base + 0) as *const i32);
                                        let l15 = *((base + 4) as *const i32);
                                        let len16 = l15 as usize;
                                        let bytes16 =
                                            Vec::from_raw_parts(l14 as *mut _, len16, len16);
                                        let l17 = *((base + 8) as *const i32);
                                        let l18 = *((base + 12) as *const i32);
                                        let len19 = l18 as usize;
                                        let bytes19 =
                                            Vec::from_raw_parts(l17 as *mut _, len19, len19);

                                        (
                                            wit_bindgen::rt::string_lift(bytes16),
                                            wit_bindgen::rt::string_lift(bytes19),
                                        )
                                    };
                                    result20.push(e20);
                                }
                                wit_bindgen::rt::dealloc(base20, (len20 as usize) * 16, 4);
                                let l21 = i32::from(*((ptr9 + 16) as *const u8));

                                super::super::super::land::http::http_types::Response {
                                    status: l11 as u16,
                                    headers: result20,
                                    body: match l21 {
                                        0 => None,
                                        1 => {
                                            let e = {
                                                let l22 = *((ptr9 + 20) as *const i32);

                                                l22 as u32
                                            };
                                            Some(e)
                                        }
                                        _ => wit_bindgen::rt::invalid_enum_discriminant(),
                                    },
                                }
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l23 = i32::from(*((ptr9 + 4) as *const u8));

                                super::super::super::land::http::http_types::RequestError::_lift(
                                    l23 as u8,
                                )
                            };
                            Err(e)
                        }
                        _ => wit_bindgen::rt::invalid_enum_discriminant(),
                    }
                }
            }
        }
    }
}

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:http-service"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1755] = [
    3, 0, 12, 104, 116, 116, 112, 45, 115, 101, 114, 118, 105, 99, 101, 0, 97, 115, 109, 13, 0, 1,
    0, 7, 204, 12, 1, 65, 4, 1, 65, 6, 1, 66, 22, 1, 123, 4, 0, 16, 104, 116, 116, 112, 45, 115,
    116, 97, 116, 117, 115, 45, 99, 111, 100, 101, 3, 0, 0, 1, 115, 4, 0, 11, 104, 116, 116, 112,
    45, 109, 101, 116, 104, 111, 100, 3, 0, 2, 1, 111, 2, 115, 115, 1, 112, 4, 4, 0, 12, 104, 116,
    116, 112, 45, 104, 101, 97, 100, 101, 114, 115, 3, 0, 5, 1, 115, 4, 0, 8, 104, 116, 116, 112,
    45, 117, 114, 105, 3, 0, 7, 1, 121, 4, 0, 16, 104, 116, 116, 112, 45, 98, 111, 100, 121, 45,
    104, 97, 110, 100, 108, 101, 3, 0, 9, 1, 107, 10, 1, 114, 4, 6, 109, 101, 116, 104, 111, 100,
    3, 3, 117, 114, 105, 8, 7, 104, 101, 97, 100, 101, 114, 115, 6, 4, 98, 111, 100, 121, 11, 4, 0,
    7, 114, 101, 113, 117, 101, 115, 116, 3, 0, 12, 1, 114, 3, 6, 115, 116, 97, 116, 117, 115, 1,
    7, 104, 101, 97, 100, 101, 114, 115, 6, 4, 98, 111, 100, 121, 11, 4, 0, 8, 114, 101, 115, 112,
    111, 110, 115, 101, 3, 0, 14, 1, 109, 6, 13, 110, 101, 116, 119, 111, 114, 107, 45, 101, 114,
    114, 111, 114, 7, 116, 105, 109, 101, 111, 117, 116, 11, 105, 110, 118, 97, 108, 105, 100, 45,
    117, 114, 108, 23, 100, 101, 115, 116, 105, 110, 97, 116, 105, 111, 110, 45, 110, 111, 116, 45,
    97, 108, 108, 111, 119, 101, 100, 17, 116, 111, 111, 45, 109, 97, 110, 121, 45, 114, 101, 113,
    117, 101, 115, 116, 115, 15, 105, 110, 118, 97, 108, 105, 100, 45, 114, 101, 113, 117, 101,
    115, 116, 4, 0, 13, 114, 101, 113, 117, 101, 115, 116, 45, 101, 114, 114, 111, 114, 3, 0, 16,
    1, 109, 3, 6, 102, 111, 108, 108, 111, 119, 5, 101, 114, 114, 111, 114, 6, 109, 97, 110, 117,
    97, 108, 4, 0, 15, 114, 101, 100, 105, 114, 101, 99, 116, 45, 112, 111, 108, 105, 99, 121, 3,
    0, 18, 1, 114, 2, 7, 116, 105, 109, 101, 111, 117, 116, 121, 8, 114, 101, 100, 105, 114, 101,
    99, 116, 19, 4, 0, 15, 114, 101, 113, 117, 101, 115, 116, 45, 111, 112, 116, 105, 111, 110,
    115, 3, 0, 20, 3, 1, 20, 108, 97, 110, 100, 58, 104, 116, 116, 112, 47, 104, 116, 116, 112, 45,
    116, 121, 112, 101, 115, 5, 0, 2, 3, 0, 0, 7, 114, 101, 113, 117, 101, 115, 116, 2, 3, 0, 0, 8,
    114, 101, 115, 112, 111, 110, 115, 101, 1, 66, 6, 2, 3, 2, 1, 1, 4, 0, 7, 114, 101, 113, 117,
    101, 115, 116, 3, 0, 0, 2, 3, 2, 1, 2, 4, 0, 8, 114, 101, 115, 112, 111, 110, 115, 101, 3, 0,
    2, 1, 64, 1, 3, 114, 101, 113, 1, 0, 3, 4, 0, 14, 104, 97, 110, 100, 108, 101, 45, 114, 101,
    113, 117, 101, 115, 116, 1, 4, 4, 1, 23, 108, 97, 110, 100, 58, 104, 116, 116, 112, 47, 104,
    116, 116, 112, 45, 105, 110, 99, 111, 109, 105, 110, 103, 5, 3, 4, 1, 28, 108, 97, 110, 100,
    58, 115, 101, 114, 118, 101, 114, 108, 101, 115, 115, 47, 104, 116, 116, 112, 45, 104, 97, 110,
    100, 108, 101, 114, 4, 0, 1, 65, 11, 1, 66, 22, 1, 123, 4, 0, 16, 104, 116, 116, 112, 45, 115,
    116, 97, 116, 117, 115, 45, 99, 111, 100, 101, 3, 0, 0, 1, 115, 4, 0, 11, 104, 116, 116, 112,
    45, 109, 101, 116, 104, 111, 100, 3, 0, 2, 1, 111, 2, 115, 115, 1, 112, 4, 4, 0, 12, 104, 116,
    116, 112, 45, 104, 101, 97, 100, 101, 114, 115, 3, 0, 5, 1, 115, 4, 0, 8, 104, 116, 116, 112,
    45, 117, 114, 105, 3, 0, 7, 1, 121, 4, 0, 16, 104, 116, 116, 112, 45, 98, 111, 100, 121, 45,
    104, 97, 110, 100, 108, 101, 3, 0, 9, 1, 107, 10, 1, 114, 4, 6, 109, 101, 116, 104, 111, 100,
    3, 3, 117, 114, 105, 8, 7, 104, 101, 97, 100, 101, 114, 115, 6, 4, 98, 111, 100, 121, 11, 4, 0,
    7, 114, 101, 113, 117, 101, 115, 116, 3, 0, 12, 1, 114, 3, 6, 115, 116, 97, 116, 117, 115, 1,
    7, 104, 101, 97, 100, 101, 114, 115, 6, 4, 98, 111, 100, 121, 11, 4, 0, 8, 114, 101, 115, 112,
    111, 110, 115, 101, 3, 0, 14, 1, 109, 6, 13, 110, 101, 116, 119, 111, 114, 107, 45, 101, 114,
    114, 111, 114, 7, 116, 105, 109, 101, 111, 117, 116, 11, 105, 110, 118, 97, 108, 105, 100, 45,
    117, 114, 108, 23, 100, 101, 115, 116, 105, 110, 97, 116, 105, 111, 110, 45, 110, 111, 116, 45,
    97, 108, 108, 111, 119, 101, 100, 17, 116, 111, 111, 45, 109, 97, 110, 121, 45, 114, 101, 113,
    117, 101, 115, 116, 115, 15, 105, 110, 118, 97, 108, 105, 100, 45, 114, 101, 113, 117, 101,
    115, 116, 4, 0, 13, 114, 101, 113, 117, 101, 115, 116, 45, 101, 114, 114, 111, 114, 3, 0, 16,
    1, 109, 3, 6, 102, 111, 108, 108, 111, 119, 5, 101, 114, 114, 111, 114, 6, 109, 97, 110, 117,
    97, 108, 4, 0, 15, 114, 101, 100, 105, 114, 101, 99, 116, 45, 112, 111, 108, 105, 99, 121, 3,
    0, 18, 1, 114, 2, 7, 116, 105, 109, 101, 111, 117, 116, 121, 8, 114, 101, 100, 105, 114, 101,
    99, 116, 19, 4, 0, 15, 114, 101, 113, 117, 101, 115, 116, 45, 111, 112, 116, 105, 111, 110,
    115, 3, 0, 20, 3, 1, 20, 108, 97, 110, 100, 58, 104, 116, 116, 112, 47, 104, 116, 116, 112, 45,
    116, 121, 112, 101, 115, 5, 0, 2, 3, 0, 0, 16, 104, 116, 116, 112, 45, 98, 111, 100, 121, 45,
    104, 97, 110, 100, 108, 101, 1, 66, 19, 2, 3, 2, 1, 1, 4, 0, 16, 104, 116, 116, 112, 45, 98,
    111, 100, 121, 45, 104, 97, 110, 100, 108, 101, 3, 0, 0, 1, 113, 4, 14, 105, 110, 118, 97, 108,
    105, 100, 45, 104, 97, 110, 100, 108, 101, 0, 0, 9, 114, 101, 97, 100, 45, 111, 110, 108, 121,
    0, 0, 11, 114, 101, 97, 100, 45, 102, 97, 105, 108, 101, 100, 1, 115, 0, 12, 119, 114, 105,
    116, 101, 45, 102, 97, 105, 108, 101, 100, 1, 115, 0, 4, 0, 10, 98, 111, 100, 121, 45, 101,
    114, 114, 111, 114, 3, 0, 2, 1, 112, 125, 1, 111, 2, 4, 127, 1, 106, 1, 5, 1, 3, 1, 64, 1, 6,
    104, 97, 110, 100, 108, 101, 1, 0, 6, 4, 0, 14, 104, 116, 116, 112, 45, 98, 111, 100, 121, 45,
    114, 101, 97, 100, 1, 7, 1, 106, 1, 4, 1, 3, 1, 64, 1, 6, 104, 97, 110, 100, 108, 101, 1, 0, 8,
    4, 0, 18, 104, 116, 116, 112, 45, 98, 111, 100, 121, 45, 114, 101, 97, 100, 45, 97, 108, 108,
    1, 9, 1, 106, 1, 119, 1, 3, 1, 64, 2, 6, 104, 97, 110, 100, 108, 101, 1, 4, 100, 97, 116, 97,
    4, 0, 10, 4, 0, 15, 104, 116, 116, 112, 45, 98, 111, 100, 121, 45, 119, 114, 105, 116, 101, 1,
    11, 1, 106, 1, 1, 1, 3, 1, 64, 0, 0, 12, 4, 0, 13, 104, 116, 116, 112, 45, 98, 111, 100, 121,
    45, 110, 101, 119, 1, 13, 4, 0, 20, 104, 116, 116, 112, 45, 98, 111, 100, 121, 45, 110, 101,
    119, 45, 115, 116, 114, 101, 97, 109, 1, 13, 3, 1, 19, 108, 97, 110, 100, 58, 104, 116, 116,
    112, 47, 104, 116, 116, 112, 45, 98, 111, 100, 121, 5, 2, 2, 3, 0, 0, 7, 114, 101, 113, 117,
    101, 115, 116, 2, 3, 0, 0, 8, 114, 101, 115, 112, 111, 110, 115, 101, 2, 3, 0, 0, 13, 114, 101,
    113, 117, 101, 115, 116, 45, 101, 114, 114, 111, 114, 2, 3, 0, 0, 15, 114, 101, 113, 117, 101,
    115, 116, 45, 111, 112, 116, 105, 111, 110, 115, 1, 66, 11, 2, 3, 2, 1, 3, 4, 0, 7, 114, 101,
    113, 117, 101, 115, 116, 3, 0, 0, 2, 3, 2, 1, 4, 4, 0, 8, 114, 101, 115, 112, 111, 110, 115,
    101, 3, 0, 2, 2, 3, 2, 1, 5, 4, 0, 13, 114, 101, 113, 117, 101, 115, 116, 45, 101, 114, 114,
    111, 114, 3, 0, 4, 2, 3, 2, 1, 6, 4, 0, 15, 114, 101, 113, 117, 101, 115, 116, 45, 111, 112,
    116, 105, 111, 110, 115, 3, 0, 6, 1, 106, 1, 3, 1, 5, 1, 64, 2, 3, 114, 101, 113, 1, 7, 111,
    112, 116, 105, 111, 110, 115, 7, 0, 8, 4, 0, 13, 102, 101, 116, 99, 104, 45, 114, 101, 113,
    117, 101, 115, 116, 1, 9, 3, 1, 23, 108, 97, 110, 100, 58, 104, 116, 116, 112, 47, 104, 116,
    116, 112, 45, 111, 117, 116, 103, 111, 105, 110, 103, 5, 7, 4, 1, 28, 108, 97, 110, 100, 58,
    115, 101, 114, 118, 101, 114, 108, 101, 115, 115, 47, 104, 116, 116, 112, 45, 115, 101, 114,
    118, 105, 99, 101, 4, 1, 11, 25, 1, 1, 19, 108, 97, 110, 100, 58, 115, 101, 114, 118, 101, 114,
    108, 101, 115, 115, 47, 119, 105, 116, 3, 0, 0, 0, 16, 12, 112, 97, 99, 107, 97, 103, 101, 45,
    100, 111, 99, 115, 0, 123, 125, 0, 70, 9, 112, 114, 111, 100, 117, 99, 101, 114, 115, 1, 12,
    112, 114, 111, 99, 101, 115, 115, 101, 100, 45, 98, 121, 2, 13, 119, 105, 116, 45, 99, 111,
    109, 112, 111, 110, 101, 110, 116, 6, 48, 46, 49, 54, 46, 48, 16, 119, 105, 116, 45, 98, 105,
    110, 100, 103, 101, 110, 45, 114, 117, 115, 116, 6, 48, 46, 49, 51, 46, 48,
];

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_section() {}
