//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub password: String,
    pub password_salt: String,
    pub name: String,
    pub nick_name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub gravatar: String,
    pub status: String,
    pub role: String,
    pub origin_provider: String,
    pub origin_user_id: Option<String>,
    pub origin_email_id: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub last_login_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
