//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uuid: String,
    pub password: String,
    pub password_salt: String,
    pub name: String,
    pub display_name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub avatar_url: String,
    pub phone: Option<String>,
    pub status: String,
    pub role: String,
    pub created_by: String,
    pub oauth_social: Option<String>,
    pub oauth_user_id: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
