interface http-incoming-iface {
    use pkg.http-types.{request,response}

    // handle request function
    handle-request: func(req: request) -> response
}

interface http-outgoing-iface {
    use pkg.http-types.{request,response,request-options,request-error}

    // handle response function
    fetch: func(req: request, options: request-options) -> result<response,request-error>
}

// export http-incoming
default world http-interface {
    export http-incoming: self.http-incoming-iface
    import http-outgoing: self.http-outgoing-iface
}