//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "project_deployment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub owner_id: i32,
    pub project_id: i32,
    #[sea_orm(unique)]
    pub domain: String,
    pub prod_domain: String,
    #[sea_orm(unique)]
    pub uuid: String,
    pub storage_path: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub prod_status: i32,
    pub deploy_status: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
