//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "deploy_task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub owner_id: i32,
    pub project_id: i32,
    pub deploy_id: i32,
    pub task_id: String,
    pub task_type: String,
    pub worker_id: i32,
    pub worker_ip: String,
    #[sea_orm(column_type = "Text")]
    pub task_content: String,
    pub status: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub message: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
